"use server";
import { GoogleGenAI } from "@google/genai";
import saveSummary from "../firebase/saveSummary";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
export async function generateSummary(
  userInput: string,
  summaryType: "good-summary" | "bad-summary",
) {
  let system = "";
  if (summaryType === "good-summary") {
    system = `Based on the following feedback data, generate a concise summary highlighting the key strengths and positive aspects. Focus on what is going well and the areas of excellence. Keep it clear, practical, and actionable for improvement.\n\n${userInput}`;
  } else if (summaryType === "bad-summary") {
    system = `Based on the following feedback data, generate a concise summary highlighting the key weaknesses and areas for improvement. Focus on what is not going well and the aspects that need attention. Keep it clear, practical, and actionable for improvement.\n\n${userInput}`;
  }
  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: system,
    });
    const markdown = response.text?.trim();

    if (!markdown) {
      throw new Error("No report content generated by Gemini.");
    }

    await saveSummary(markdown, summaryType);
    console.log("Generated Summary Markdown:", markdown);
    return markdown;
  } catch (error) {
    console.error("Error generating summary:", error);
    throw new Error("Failed to generate summary");
  }
}
