"use server";
import { GoogleGenAI } from "@google/genai";
import saveReport from "../firebase/saveReport";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

function buildReportPrompt(statsInput: string) {
  return `You are a feedback performance analyst.
  Input statistics (JSON):
  ${statsInput}

  Task:
  - Generate a short report for one user based on the statistics.
  - Keep it simple, clear, and practical.
  - Focus on these goals:
    1) Tell the user their current position.
    2) Explain pros (strengths).
    3) Explain cons (problems).
    4) Give general tips for improvement.

  Output rules:
  - RESPOND IN VALID MARKDOWN ONLY.
  - Do not include JSON, code blocks, or extra metadata.
  - Use this exact section structure:

  # Performance Report
  ## Your Position
  ## advantages aspects
  ## disadvantages aspects
  ## General Tips For Improvement

  - Keep the report concise and readable.`;
}

export async function generateReport(
  userInput: string,
): Promise<string | null> {
  try {
    if (!userInput || typeof userInput !== "string") {
      throw new Error(
        "Invalid report input. Expected non-empty stats JSON string.",
      );
    }

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: buildReportPrompt(userInput),
    });

    const markdown = response.text?.trim();

    if (!markdown) {
      throw new Error("No report content generated by Gemini.");
    }

    await saveReport(markdown);
    console.log("Generated Report Markdown:", markdown);
    return markdown;
  } catch (error) {
    console.error("Error generating report:", error);
    return null;
  }
}
