"use server";
import { GoogleGenAI, Type, Schema } from "@google/genai";
import saveFeedbackResult from "../firebase/saveFeedbackResult";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

const responseSchema: Schema = {
  type: Type.OBJECT,
  properties: {
    sentiment: {
      type: Type.STRING,
      description:
        "Classify as 'positive', 'negative ^^DO NOT SAY IT IS BEGATIVE ANLESS ITS 80% NEGATIVE^^','neutral'.",
    },
    summary: {
      type: Type.STRING,
      description:
        "An extremely brief summary of the feedback, strictly 50% of the original length.",
    },
    analysis_feedback: {
      type: Type.STRING,
      description:
        "A brief analytical insight or recommended action based on the feedback.",
    },
    key_strengths: {
      type: Type.ARRAY,
      items: { type: Type.STRING },
      description: "List of positive operational aspects mentioned.",
    },
    key_problems: {
      type: Type.ARRAY,
      items: { type: Type.STRING },
      description: "List of operational issues mentioned.",
    },
  },
  required: [
    "sentiment",
    "summary",
    "analysis_feedback",
    "key_strengths",
    "key_problems",
  ],
};

export async function analysFeedback(userInput: string) {
  try {
    if (!userInput || typeof userInput !== "string") {
      return console.error(
        "Invalid input: userInput must be a non-empty string.",
      );
    }

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: `Analyze the following customer feedback for a specialty coffee shop: "${userInput}"`,
      config: {
        responseMimeType: "application/json",
        responseSchema: responseSchema,
      },
    });

    if (!response.text) {
      throw new Error("No response generated by the API.");
    }

    const result = JSON.parse(response.text);

    await saveFeedbackResult(userInput, result);

    return result;
  } catch (error) {
    return console.error("AI Analysis Error:", error);
  }
}
